In [1]:
import numpy as np

x_trn = np.array([[24000,8],
                 [30000,2],
                 [35000,7],
                 [34500,1]])
x_tst= np.array([[34000,7],
                 [12000,1]])

In [7]:
col1= x_trn[:,0]
trf_col1=((col1 - col1.mean())/np.std(col1))
print(np.mean(trf_col1), np.std(trf_col1))

0.0 1.0


In [8]:
col2= x_trn[:,1]
trf_col2=((col2 - col2.mean())/np.std(col2))
print(np.mean(trf_col2), np.std(trf_col2))

0.0 1.0


In [9]:
#All columns at once
means = x_trn.mean(axis=0)
stds= x_trn.std(axis=0)
print((x_trn-means)/stds)


[[-1.55501304  1.15079291]
 [-0.19791075 -0.82199494]
 [ 0.93300782  0.82199494]
 [ 0.81991597 -1.15079291]]


In [16]:
print((x_trn-means)/stds)

[[-1.55501304  1.15079291]
 [-0.19791075 -0.82199494]
 [ 0.93300782  0.82199494]
 [ 0.81991597 -1.15079291]]


In [17]:
print((x_tst-means)/stds)

[[ 0.70682411  0.82199494]
 [-4.26921761 -1.15079291]]


In [18]:
print(means)

[3.0875e+04 4.5000e+00]


In [19]:
print(stds)

[4.42118480e+03 3.04138127e+00]


In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:

scaler= StandardScaler()
print(scaler.fit_transform(x_trn))


[[-1.55501304  1.15079291]
 [-0.19791075 -0.82199494]
 [ 0.93300782  0.82199494]
 [ 0.81991597 -1.15079291]]


In [22]:
print(scaler.transform(x_tst))

[[ 0.70682411  0.82199494]
 [-4.26921761 -1.15079291]]


In [23]:
print(scaler.mean_)

[3.0875e+04 4.5000e+00]


In [24]:
print(scaler.scale_)

[4.42118480e+03 3.04138127e+00]


In [49]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,r2_score
from sklearn.metrics import log_loss,accuracy_score
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedGroupKFold,GridSearchCV, StratifiedKFold

In [50]:
img= pd.read_csv('Image_Segmention.csv')
lbl= LabelEncoder()
img['Class']=lbl.fit_transform(img['Class'])
print(lbl.classes_)


['BRICKFACE' 'CEMENT' 'FOLIAGE' 'GRASS' 'PATH' 'SKY' 'WINDOW']


In [51]:
X=img.drop('Class',axis=1)
y= img['Class']

In [59]:
X_train, X_test,y_train, y_test= train_test_split(X,y,test_size=0.3,random_state=23)

In [70]:
y_pred_prob= knn.predict_proba(X_test)

/home/dai/anaconda3/lib/python3.11/site-packages/sklearn/base.py:458: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


In [60]:
kfold= StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=23)
knn= KNeighborsClassifier()

In [61]:
params= {'n_neighbors':np.arange(1,11)}
kfold= StratifiedKFold(n_splits=5, shuffle=True, random_state=23)
knm= KNeighborsClassifier()

In [62]:
#log loss
gcv= GridSearchCV(knm,param_grid=params, cv=kfold, scoring='neg_log_loss')

In [63]:
gcv.fit(X,y)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=23, shuffle=True),
             estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])},
             scoring='neg_log_loss')

In [64]:
gcv.best_params_

{'n_neighbors': 10}

In [65]:
gcv.best_score_

-0.8815302233391723

In [66]:
#with scaling

scaler= StandardScaler()
X_scl_trn= scaler.fit_transform(X_train)
X_scl_tst= scaler.transform(X_test)

In [71]:
'''knn= KNeighborsClassifier(n_neighbors=1)
knn.fit(X_scl_trn,y_train)
y_pred= knn.predict(X_scl_trn)
print(accuracy_score(y_test,y_pred))'''

ValueError: Found input variables with inconsistent numbers of samples: [63, 146]

In [69]:
y_pred_prob= knn.predict_proba(X_sci_tst)
print(log_loss(y_test,y_pred_prob))

NameError: name 'X_sci_tst' is not defined

In [72]:
# with pipeline

from sklearn.pipeline import Pipeline
scaler= StandardScaler()
knn= KNeighborsClassifier(n_neighbors=1)
pipe= Pipeline([('SCL',scaler),('KNN',knn)])
pipe.fit(X_train,y_train)
y_pred= pipe.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.873015873015873


In [73]:
y_pred_prob= pipe.predict_proba(X_test)
print(log_loss(y_test,y_pred_prob))

4.576971858935513


In [74]:
# Grid Search CV

kfold= StratifiedKFold(n_splits=5,shuffle=True, random_state=23)
scaler= StandardScaler()
knn = KNeighborsClassifier()
pipe = Pipeline([('SCL',scaler),('KNN',knn)])

In [76]:
print(pipe.get_params())

{'memory': None, 'steps': [('SCL', StandardScaler()), ('KNN', KNeighborsClassifier())], 'verbose': False, 'SCL': StandardScaler(), 'KNN': KNeighborsClassifier(), 'SCL__copy': True, 'SCL__with_mean': True, 'SCL__with_std': True, 'KNN__algorithm': 'auto', 'KNN__leaf_size': 30, 'KNN__metric': 'minkowski', 'KNN__metric_params': None, 'KNN__n_jobs': None, 'KNN__n_neighbors': 5, 'KNN__p': 2, 'KNN__weights': 'uniform'}


In [77]:
params={'KNN_n_neighbors':np.arange(1,11)}

In [78]:
#log loss

gcv=GridSearchCV(pipe, param_grid=params, cv=kfold,scoring='neg_log_loss')
gcv.fit(X,y)

ValueError: Invalid parameter 'KNN_n_neighbors' for estimator Pipeline(steps=[('SCL', StandardScaler()), ('KNN', KNeighborsClassifier())]). Valid parameters are: ['memory', 'steps', 'verbose'].

In [79]:
print(gcv.best_params_)
print(gcv.best_score_)

AttributeError: 'GridSearchCV' object has no attribute 'best_params_'