### 1. Write a Pandas program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

In [1]:
import pandas as pd
import numpy as np

In [2]:
s=pd.Series(np.array([1,2,3,4,5,6]))
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [3]:
type(s)

pandas.core.series.Series

### 2. Write a Pandas program to convert a Panda module Series to Python list and it's type.

In [5]:
l=list(s)
type(l)

list

### 3. Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
### Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [7]:
s1=pd.Series([2, 4, 6, 8, 10])
s2=pd.Series([1, 3, 5, 7, 9])
s1+s2

0     3
1     7
2    11
3    15
4    19
dtype: int64

In [8]:
s1-s2

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [9]:
s1/s2

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [10]:
s1*s2

0     2
1    12
2    30
3    56
4    90
dtype: int64

### 4. Write a Pandas program to compare the elements of the two Pandas Series.
### Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [11]:
s1=pd.Series([2, 4, 6, 8, 10])
s2=pd.Series([1, 3, 5, 7, 10])
s1<s2

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [12]:
s1>s2

0     True
1     True
2     True
3     True
4    False
dtype: bool

In [13]:
s1==s2

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [14]:
s1!=s2

0     True
1     True
2     True
3     True
4    False
dtype: bool

In [15]:
s1<=s2

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [17]:
s1>=s2

0    True
1    True
2    True
3    True
4    True
dtype: bool

### 5.Write a Pandas program to convert a dictionary to a Pandas series.

In [18]:
d={'a':12,'b':56,'c':89}
s=pd.Series(data=d)

In [20]:
print(s)
print(type(s))

a    12
b    56
c    89
dtype: int64
<class 'pandas.core.series.Series'>


### 6. Write a Pandas program to convert a NumPy array to a Pandas series.

In [22]:
a=np.arange(1,20)
s=pd.Series(data=a)
s

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
dtype: int64

### 7. Write a Pandas program to change the data type of given a column or a Series.

In [33]:
s=pd.Series([100,200,'python',300.12,400])
s

0       100
1       200
2    python
3    300.12
4       400
dtype: object

In [35]:
s=pd.to_numeric(s,errors='coerce')
s

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

### 8. Write a Pandas program to convert the first column of a DataFrame as a Series.

In [11]:
df=pd.DataFrame(data={'col1':[1,2,3,4,7,11],'col2':[4,5,6,9,5,0],'col3':[7,5,8,12,1,11]})
print("Original Dataframe\n",df)
s=pd.Series(df['col1'])
print("1st Column as Data Series\n",s)
print(type(s))

Original Dataframe
    col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11
1st Column as Data Series
 0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>


### 9. Write a Pandas program to convert a given Series to an array.

In [20]:
s=pd.Series([100,200,'python',300.12,400])
print("Original Data Series:")
print(s)
print("Series to an array")
a=s.values
print(a)
print(type(a))

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
[100 200 'python' 300.12 400]
<class 'numpy.ndarray'>


### 10. Write a Pandas program to convert Series of lists to one Series.

In [24]:
s=pd.Series([['Red', 'Green', 'White'],['Red', 'Black'],['Yellow']])
print("Original Series of list")
print(s)
print("One Series")
s1=s.apply(pd.Series).stack().reset_index(drop=True)
print(s1)

Original Series of list
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object
One Series
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object


### 11. Write a Pandas program to sort a given Series.

In [27]:
s=pd.Series(['100','200','python','300.12','400'])
print("Original Series of list")
print(s)
s1=pd.Series(s).sort_values()
s1

Original Series of list
0       100
1       200
2    python
3    300.12
4       400
dtype: object


0       100
1       200
3    300.12
4       400
2    python
dtype: object

### 12. Write a Pandas program to add some data to an existing Series.

In [34]:
s=pd.Series(['100','200','python','300.12','400'])
print("Original Series of list")
print(s)
#s=s.append(pd.Series(['500','php']),ignore_index=True)
#s
s=pd.concat([s,pd.Series(['500','php'])],ignore_index=True)
s

Original Series of list
0       100
1       200
2    python
3    300.12
4       400
dtype: object


0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: object

### 13. Write a Pandas program to create a subset of a given series based on value and condition.

In [36]:
print("Original Data Series:")
s=pd.Series(np.arange(0,11))
print(s)
print("Subset of the above Data Series:")
print(s[s<6])

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64
Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


### 14. Write a Pandas program to change the order of index of a given series.

In [40]:
print("Original Data Series:")
s=pd.Series(data=[1,2,3,4,5],index=['A', 'B', 'C','D','E'])
print(s)
print("Subset of the above Data Series:")
s=s.reindex(index = ['E','A','D','B','C'])
s

Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Subset of the above Data Series:


E    5
A    1
D    4
B    2
C    3
dtype: int64

### 15. Write a Pandas program to create the mean and standard deviation of the data of a given Series.

In [41]:
s=pd.Series(data=[1,8,2,9,3,4,5,3])
print("mean: ",s.mean())
print("Standard Deviation: ",s.std())

mean:  4.375
Standard Deviation:  2.8252686345094435


### 16. Write a Pandas program to get the items of a given series not present in another given series.

In [46]:
print("Original Data Series:")
s1=pd.Series(data=[1,2,3,4,5])
s2=pd.Series(data=[6,2,8,4,10])
print(s1)
print(s2)
print("Items of sr1 not present in sr2:")
print(s1[~s1.isin(s2)])

Original Data Series:
0    1
1    2
2    3
3    4
4    5
dtype: int64
0     6
1     2
2     8
3     4
4    10
dtype: int64
Items of sr1 not present in sr2:
0    1
2    3
4    5
dtype: int64


### 17. Write a Pandas program to get the items which are not common of two given series.

In [51]:
print("Original Data Series:")
s1=pd.Series(data=[1,2,3,4,5])
s2=pd.Series(data=[6,2,8,4,10])
print(s1)
print(s2)
print("Items which are not common in s1 and s2: ")
s11=s1[~s1.isin(s2)]
s12=s2[~s2.isin(s1)]
print(pd.concat([s11,s12],ignore_index=True))

Original Data Series:
0    1
1    2
2    3
3    4
4    5
dtype: int64
0     6
1     2
2     8
3     4
4    10
dtype: int64
Items which are not common in s1 and s2: 
0     1
1     3
2     5
3     6
4     8
5    10
dtype: int64


### 18. Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series.

In [61]:
s=pd.Series(data=[1,8,2,9,3,4,5,3])
print("Minimum, 25th percentile, median, 75th, and maximum of a given series:")
print(np.percentile(s,[0,25,50,75,100]))

Minimum, 25th percentile, median, 75th, and maximum of a given series:
[1.   2.75 3.5  5.75 9.  ]


### 19. Write a Pandas program to calculate the frequency counts of each unique value of a given series.

In [62]:
s=pd.Series(np.random.randint(1,10,20))
s

0     3
1     9
2     8
3     3
4     6
5     2
6     2
7     6
8     5
9     7
10    5
11    4
12    1
13    9
14    7
15    1
16    5
17    2
18    4
19    8
dtype: int64

In [65]:
s.value_counts()

2    3
5    3
3    2
9    2
8    2
6    2
7    2
4    2
1    2
dtype: int64

### 20. Write a Pandas program to display most frequent value in a given series and replace everything else as 'Other' in the series.

In [66]:
s=pd.Series(np.random.randint(1,10,20))
s

0     8
1     5
2     7
3     1
4     3
5     7
6     3
7     6
8     2
9     7
10    1
11    1
12    2
13    6
14    8
15    7
16    9
17    3
18    1
19    8
dtype: int64

In [77]:
print("Top 3 Frequencies: ")
s.value_counts()[0:3]

Top 3 Frequencies: 


7    4
1    4
8    3
dtype: int64

In [72]:
s1=s.map(lambda x:x if x==s.value_counts().index[0] else 'Other')
s1

0     Other
1     Other
2         7
3     Other
4     Other
5         7
6     Other
7     Other
8     Other
9         7
10    Other
11    Other
12    Other
13    Other
14    Other
15        7
16    Other
17    Other
18    Other
19    Other
dtype: object

### 21. Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series.

In [79]:
s=pd.Series(data=[1,15,8,6,9,5,1,10,1])
print("original Series:")
print(s)
res=np.where(s%5==0)
print("the positions of numbers that are multiples of 5 ")
print(res)

original Series:
0     1
1    15
2     8
3     6
4     9
5     5
6     1
7    10
8     1
dtype: int64
the positions of numbers that are multiples of 5 
(array([1, 5, 7]),)


### 22. Write a Pandas program to extract items at given positions of a given series.

In [83]:
s=pd.Series(np.random.randint(0,10,20))
print("original series")
print(s)
list1=[5,8,11,15]
res=s.take(list1)
print(res)

original series
0     5
1     4
2     1
3     2
4     0
5     6
6     3
7     4
8     9
9     1
10    1
11    2
12    3
13    9
14    3
15    9
16    3
17    3
18    7
19    0
dtype: int64
5     6
8     9
11    2
15    9
dtype: int64


### 23. Write a Pandas program to get the positions of items of a given series in another given series.

In [88]:
s1=pd.Series(list('467946123'))
s2=pd.Series(list('379'))
print("original Series:")
print(s1)
print(s2)
res = [pd.Index(s1).get_loc(i) for i in s2]
print("the positions of items of a given series in another given series.")
print(res)

original Series:
0    4
1    6
2    7
3    9
4    4
5    6
6    1
7    2
8    3
dtype: object
0    3
1    7
2    9
dtype: object
the positions of items of a given series in another given series.
[8, 2, 3]


### 24. Write a Pandas program convert the first and last character of each word to upper case in each word of a given series.

In [93]:
s1=pd.Series(data=['php','java','c#','python'])
print("original Series: ")
print(s1)
result=s1.map(lambda x:x[0].upper() + x[1:-1] + x[-1].upper())
print(result)

original Series: 
0       php
1      java
2        c#
3    python
dtype: object
0       PhP
1      JavA
2        C#
3    PythoN
dtype: object


### 25. Write a Pandas program to calculate the number of characters in each word in a given series.

In [94]:
s1=pd.Series(data=['php','java','c#','python'])
print("original Series: ")
print(s1)
result=s1.map(lambda x: len(x))
print(result)

original Series: 
0       php
1      java
2        c#
3    python
dtype: object
0    3
1    4
2    2
3    6
dtype: int64


### 26. Write a Pandas program to compute difference of differences between consecutive numbers of a given series.

In [97]:
s1=pd.Series(data=[1,3,4,5,8,11,16])
print("original Series: ")
print(s1)
print(s1.diff().to_list)
print(s1.diff().diff().to_list)

original Series: 
0     1
1     3
2     4
3     5
4     8
5    11
6    16
dtype: int64
<bound method IndexOpsMixin.tolist of 0    NaN
1    2.0
2    1.0
3    1.0
4    3.0
5    3.0
6    5.0
dtype: float64>
<bound method IndexOpsMixin.tolist of 0    NaN
1    NaN
2   -1.0
3    0.0
4    2.0
5    0.0
6    2.0
dtype: float64>


### 27. Write a Pandas program to convert a series of date strings to a timeseries.

In [101]:
s1=pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12 T13:45:40', '2019-04-06T11:20'] )
print("original series ")
print(s1)
print("timeseries")
print(pd.to_datetime(s1))

original series 
0             01 Jan 2015
1              10-02-2016
2                20180307
3              2014/05/06
4    2016-04-12 T13:45:40
5        2019-04-06T11:20
dtype: object
timeseries
0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 13:45:40
5   2019-04-06 11:20:00
dtype: datetime64[ns]


### 28. Write a Pandas program to get the day of month, day of year, week number and day of week from a given series of date strings.

In [118]:
from dateutil.parser import parse
s1=pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12 T13:45:40', '2019-04-06T11:20'] )
print("original series ")
print(s1)
s1= s1.map(lambda x :parse(x))
print("the day of month")
print(s1.dt.day.tolist())
print("the day of year")
print(s1.dt.dayofyear.tolist())
print("week number")
print(s1.dt.isocalendar().week)

original series 
0             01 Jan 2015
1              10-02-2016
2                20180307
3              2014/05/06
4    2016-04-12 T13:45:40
5        2019-04-06T11:20
dtype: object
the day of month
[1, 2, 7, 6, 12, 6]
the day of year
[1, 276, 66, 126, 103, 96]
week number
0     1
1    39
2    10
3    19
4    15
5    14
Name: week, dtype: UInt32


### 29. Write a Pandas program to convert year-month string to dates adding a specified day of the month.

In [124]:
s1=pd.Series(['Jan 2015', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019'])
print("original series")
print(s1)
print("new date")
res=s1.map(lambda x: parse('15' +x))
print(res)

original series
0    Jan 2015
1    Feb 2016
2    Mar 2017
3    Apr 2018
4    May 2019
dtype: object
new date
0   2015-01-15
1   2016-02-15
2   2017-03-15
3   2018-04-15
4   2019-05-15
dtype: datetime64[ns]


### 30. Write a Pandas program to filter words from a given series that contain atleast two vowels.

In [131]:
from collections import Counter
s1=pd.Series(['Red','Green','Orange','Pink','Yellow','White'])
print("Original series:")
print(s1)
res=s1.map(lambda x: sum([Counter(x.lower()).get(i,0) for i in list('aeiou')])>=2)
print(s1[res])

Original series:
0       Red
1     Green
2    Orange
3      Pink
4    Yellow
5     White
dtype: object
1     Green
2    Orange
4    Yellow
5     White
dtype: object


### 31. Write a Pandas program to compute the Euclidean distance between two given series.
### Euclidean distance
### From Wikipedia,
### In mathematics, the Euclidean distance or Euclidean metric is the "ordinary" straight-line distance between two points in Euclidean space. With this distance, Euclidean space becomes a metric space. The associated norm is called the Euclidean norm.

In [134]:
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([11,8,7,5,6,5,3,4,7,1])
print("original Series: ")
print(s1)
print(s2)
print('\nEuclidean distance between two given series')
print(np.linalg.norm(s1-s2))

original Series: 
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
0    11
1     8
2     7
3     5
4     6
5     5
6     3
7     4
8     7
9     1
dtype: int64

Euclidean distance between two given series
16.492422502470642


### 32. Write a Pandas program to find the positions of the values neighboured by smaller values on both sides in a given series.

In [136]:
s2=pd.Series([1,8,7,5,6,5,3,4,7,1])


In [137]:
t=np.diff(s2)
t

array([ 7, -1, -2,  1, -1, -2,  1,  3, -6])

In [138]:
t=np.sign(t)
t

array([ 1, -1, -1,  1, -1, -1,  1,  1, -1])

In [139]:
t=np.diff(t)
t

array([-2,  0,  2, -2,  0,  2,  0, -2])

In [147]:
np.where(t==-2)[0]

array([0, 3, 7])

In [148]:
np.where(t==-2)[0]+1

array([1, 4, 8])

### 33. Write a Pandas program to replace missing white spaces in a given string with the least frequent character.

### 34. Write a Pandas program to compute the autocorrelations of a given numeric series.
### From Wikipedia:
### Autocorrelation, also known as serial correlation, is the correlation of a signal with a delayed copy of itself as a function of delay. Informally, it is the similarity between observations as a function of the time lag between them.

### 35. Write a Pandas program to create a TimeSeries to display all the Sundays of given year.

### 36. Write a Pandas program to convert given series into a dataframe with its index as another column on the dataframe.

### 37. Write a Pandas program to stack two given series vertically and horizontally.

### 38. Write a Pandas program to check the equality of two given series.

### 39. Write a Pandas program to find the index of the first occurrence of the smallest and largest value of a given series.

### 40. Write a Pandas program to check inequality over the index axis of a given dataframe and a given series.

###

###

###

###

###

###

###

###

###

###

###

###

###